name: Build and tests.

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  tests:
    runs-on: windows-latest

    steps:
    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: ${{ runner.os }}-QtCache

    - uses: actions/checkout@v2

    - name: Install Qt
      uses: jurplel/install-qt-action@v2.10.0
      with:
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
        host: 'windows'
        arch: 'win64_msvc2017_64'
        tools: 'tools_ifw,4.0,qt.tools.ifw.40 tools_qtcreator,4.13.2-0,qt.tools.qtcreator'
        extra: '--external 7z'

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DENABLE_UNIT_TESTS=ON

    - name: Tests
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: |
        cmake --build . --config $BUILD_TYPE
        mv ../build/bin/Release/UnitTests.exe $Qt5_Dir/bin

    - name: Run tests bash🚀
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: $Qt5_Dir/bin/UnitTests.exe

  build:
    runs-on: windows-latest

    steps:
    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: ${{ runner.os }}-QtCache

    - uses: actions/checkout@v2

    - name: Install Qt
      uses: jurplel/install-qt-action@v2.10.0
      with:
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
        host: 'windows'
        arch: 'win64_msvc2017_64'
        tools: 'tools_ifw,4.0,qt.tools.ifw.40 tools_qtcreator,4.13.2-0,qt.tools.qtcreator'
        extra: '--external 7z'

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DENABLE_UNIT_TESTS=OFF

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Create Installer
      shell: bash
      run: |
        cd InnoSetup 
        echo "#define Qt5_Dir \"$Qt5_Dir\"" > script.iss
        cat EvoScript.iss >> script.iss 
        ISCC.exe script.iss

    - uses: actions/upload-artifact@v2
      with:
        name: setup.exe
        path: D:/a/Evo/installer
